# Generated by Django 5.2.9 on 2026-01-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_text_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
    ]
