# Generated by Django 5.2.9 on 2026-01-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(default='NA', max_length=150),
            preserve_default=False,
        ),
    ]
