# Generated by Django 5.2.9 on 2026-01-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='defaults/default_user.png', null=True, upload_to='profiles/'),
        ),
    ]
